### PR TITLE
chore: Some modifications

### PR DESCRIPTION
**Pull request by Zaid-maker**
This PR did some modifications!

- Add package-lock.json back (bcoz why not)
- reformat the config file
- format the README.md also
- Fix 3 of 4 High Dependency Vulnerable Issue

### CODE REVIEW

**Comment by TheHellTower** [comment]
Hello,

- `package-lock.json` is not strictly needed in this project, it is automatically generated by the Node.JS package manager ([`npm`](https://www.npmjs.com)) and this file is not necessary here since we know the needed dependencies and it will be updated due to the changes I'm doing so the dependencies will change(for a few of them) or even their used version since I planned to use all the last versions of the used modules if possible and it will require a Node.JS Engine `>=16.9.0` instead of `14.x` because stay up to date is important and can help in security terms or even performances.
- I already did it on my side and maybe in the next updates it would change I planned to either change the structure of this json file or move to `.env` variables to make a more "secure" setup since they are not necessarily directly exposed if your work environment let you register them securely.
- Format the readme is for the moment useless I need to finish everything before cleaning it.

Thanks for your efforts anyway ! Hopefully you will make a few PR when the first "massive" update will be pushed !

I'm going to go a little off-topic for this PR, can you explain the use of the words `chore`, etc.. in commits in general ? I've never used them but it could potentially be useful.

Regards.

**Comment by Zaid-maker** [comment]
> Hello,
> 
> * `package-lock.json` is not strictly needed in this project, it is automatically generated by the Node.JS package manager ([`npm`](https://www.npmjs.com)) and this file is not necessary here since we know the needed dependencies and it will be updated due to the changes I'm doing so the dependencies will change(for a few of them) or even their used version since I planned to use all the last versions of the used modules if possible and it will require a Node.JS Engine `>=16.9.0` instead of `14.x` because stay up to date is important and can help in security terms or even performances.
> * I already did it on my side and maybe in the next updates it would change I planned to either change the structure of this json file or move to `.env` variables to make a more "secure" setup since they are not necessarily directly exposed if your work environment let you register them securely.
> * Format the readme is for the moment useless I need to finish everything before cleaning it.
> 
> Thanks for your efforts anyway ! Hopefully you will make a few PR when the first "massive" update will be pushed !
> 
> I'm going to go a little off-topic for this PR, can you explain the use of the words `chore`, etc.. in commits in general ? I've never used them but it could potentially be useful.
> 
> Regards.

I am using OpenAI to generate these fancy commits messages. chore means chore: updating grunt tasks etc; no production code change

So few commits are important like i fix the dependency issue etc

**Comment by TheHellTower** [comment]
> > Hello,
> > 
> > * `package-lock.json` is not strictly needed in this project, it is automatically generated by the Node.JS package manager ([`npm`](https://www.npmjs.com)) and this file is not necessary here since we know the needed dependencies and it will be updated due to the changes I'm doing so the dependencies will change(for a few of them) or even their used version since I planned to use all the last versions of the used modules if possible and it will require a Node.JS Engine `>=16.9.0` instead of `14.x` because stay up to date is important and can help in security terms or even performances.
> > * I already did it on my side and maybe in the next updates it would change I planned to either change the structure of this json file or move to `.env` variables to make a more "secure" setup since they are not necessarily directly exposed if your work environment let you register them securely.
> > * Format the readme is for the moment useless I need to finish everything before cleaning it.
> > 
> > Thanks for your efforts anyway ! Hopefully you will make a few PR when the first "massive" update will be pushed !
> > I'm going to go a little off-topic for this PR, can you explain the use of the words `chore`, etc.. in commits in general ? I've never used them but it could potentially be useful.
> > Regards.
> 
> I am using OpenAI to generate these fancy commits messages. chore means chore: updating grunt tasks etc; no production code change
> 
> So few commits are important like i fix the dependency issue etc

Okay thanks I will ask ChatGPT to go deeply in the explanation then to maybe help me get better practices for commit messages thanks.

So I will close this PR and maybe when I will have finished all the updates I will publish a preview(video) of the code. For the website design I didn't change it for the moment.

Thanks !

**Comment by Zaid-maker** [comment]
> > > Hello,
> > > 
> > > * `package-lock.json` is not strictly needed in this project, it is automatically generated by the Node.JS package manager ([`npm`](https://www.npmjs.com)) and this file is not necessary here since we know the needed dependencies and it will be updated due to the changes I'm doing so the dependencies will change(for a few of them) or even their used version since I planned to use all the last versions of the used modules if possible and it will require a Node.JS Engine `>=16.9.0` instead of `14.x` because stay up to date is important and can help in security terms or even performances.
> > > * I already did it on my side and maybe in the next updates it would change I planned to either change the structure of this json file or move to `.env` variables to make a more "secure" setup since they are not necessarily directly exposed if your work environment let you register them securely.
> > > * Format the readme is for the moment useless I need to finish everything before cleaning it.
> > > 
> > > Thanks for your efforts anyway ! Hopefully you will make a few PR when the first "massive" update will be pushed !
> > > I'm going to go a little off-topic for this PR, can you explain the use of the words `chore`, etc.. in commits in general ? I've never used them but it could potentially be useful.
> > > Regards.
> > 
> > 
> > I am using OpenAI to generate these fancy commits messages. chore means chore: updating grunt tasks etc; no production code change
> > So few commits are important like i fix the dependency issue etc
> 
> Okay thanks I will ask ChatGPT to go deeply in the explanation then to maybe help me get better practices for commit messages thanks.
> 
> So I will close this PR and maybe when I will have finished all the updates I will publish a preview(video) of the code. For the website design I didn't change it for the moment.
> 
> Thanks !

Alright i will wait for the updates you make then maybe update smh myself, if u want to know how i do the commit messages DM me on Discord DevMitza#6447 :)

**Comment by TheHellTower** [comment]
The `package-lock.json` is only good to save exact versions but is really useless here I assure you anyone respecting the requirements will be able to do the setup without, it would be useful only if in the `package.json` the specified versions was ranges and not exact versions because it would keep track of the version installed at the moment but I will update myself following the updates of the modules.

I'm not sure what you mean by "`then update something myself`", do you mean make a fork or my repository when updated to update it on your side as another [Discord-Bot-List](https://github.com/Sank6/Discord-Bot-List) fork ?

**Comment by Zaid-maker** [comment]
> The `package-lock.json` is only good to save exact versions but is really useless here I assure you anyone respecting the requirements will be able to do the setup without, it would be useful only if in the `package.json` the specified versions was ranges and not exact versions because it would keep track of the version installed at the moment but I will update myself following the updates of the modules.
> 
> I'm not sure what you mean by "`then update something myself`", do you mean make a fork or my repository when updated to update it on your side as another [Discord-Bot-List](https://github.com/Sank6/Discord-Bot-List) fork ?

I mean with that i will check for the changes i can make when you push the update.

I use package-lock widely in my projects as it helps me alot to maintain my dependencies.

**Comment by TheHellTower** [comment]
> mean with that i will check for the changes i can make when you push the update.
> 
> I use package-lock widely in my projects as it helps me alot to maintain my dependencies.

My advice regarding the `package-lock.json` is to only keep it if you give a `range` for the versions of your modules because if you specify specific versions it will not change anything and just add one "useless" file. For example it can be useless if you use specify "latest" to say you want the latest version, then the `package-lock.json` would install the last version of the module that you installed to avoid you using a versions with breaking changes(that could break your project).

**Comment by Zaid-maker** [comment]
> > mean with that i will check for the changes i can make when you push the update.
> > I use package-lock widely in my projects as it helps me alot to maintain my dependencies.
> 
> My advice regarding the `package-lock.json` is to only keep it if you give a `range` for the versions of your modules because if you specify specific versions it will not change anything and just add one "useless" file. For example it can be useful if you specify "latest" to say you want the latest version, then the `package-lock.json` would install the last version of the module that you installed to avoid you using a versions with breaking changes(that could break your project).

Read this [NPM Docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json)

**Comment by Zaid-maker** [comment]
> > mean with that i will check for the changes i can make when you push the update.
> > I use package-lock widely in my projects as it helps me alot to maintain my dependencies.
> 
> My advice regarding the `package-lock.json` is to only keep it if you give a `range` for the versions of your modules because if you specify specific versions it will not change anything and just add one "useless" file. For example it can be useful if you specify "latest" to say you want the latest version, then the `package-lock.json` would install the last version of the module that you installed to avoid you using a versions with breaking changes(that could break your project).

Let me give an example!

There is a tool called dependabot which will update the dependencies according to thier versions if any installed package got an update it will make a PR to update it and for that to work package-lock.json is important to be pushed. There are three range of package versions: Major, Minor, Patch. We can customize the behaviour of dependabot to accpet any 3 of these range.

That's why package-lock.json is important, Dependabot helps to ato update deps for you instead of doing it manaully. many big open source projects have pushed thier lock files.

**Comment by Zaid-maker** [comment]
> > > mean with that i will check for the changes i can make when you push the update.
> > > I use package-lock widely in my projects as it helps me alot to maintain my dependencies.
> > 
> > 
> > My advice regarding the `package-lock.json` is to only keep it if you give a `range` for the versions of your modules because if you specify specific versions it will not change anything and just add one "useless" file. For example it can be useful if you specify "latest" to say you want the latest version, then the `package-lock.json` would install the last version of the module that you installed to avoid you using a versions with breaking changes(that could break your project).
> 
> Let me give an example!
> 
> There is a tool called dependabot which will update the dependencies according to thier versions if any installed package got an update it will make a PR to update it and for that to work package-lock.json is important to be pushed. There are three range of package versions: Major, Minor, Patch. We can customize the behaviour of dependabot to accpet any 3 of these range.
> 
> That's why package-lock.json is important, Dependabot helps to ato update deps for you instead of doing it manaully. many big open source projects have pushed thier lock files.

**Comment by Zaid-maker** [comment]
> > > > mean with that i will check for the changes i can make when you push the update.
> > > > I use package-lock widely in my projects as it helps me alot to maintain my dependencies.
> > > 
> > > 
> > > My advice regarding the `package-lock.json` is to only keep it if you give a `range` for the versions of your modules because if you specify specific versions it will not change anything and just add one "useless" file. For example it can be useful if you specify "latest" to say you want the latest version, then the `package-lock.json` would install the last version of the module that you installed to avoid you using a versions with breaking changes(that could break your project).
> > 
> > Read this [NPM Docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json)
> 
> The thing the first purpose describe: `Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.` is literally what I said about `range` versions, if you put exact versions in your `package.json` you will also be guaranteed to get back the same dependencies. You can try if you don't think it's true, until now I got no issues and I was able to setup the project without(like you I suppose you tried the [Discord-Bot-List](https://github.com/Sank6/Discord-Bot-List) project so you should know it work well without ! The only actual issue is outdated packages :)).
> 
> - `Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.` for this, I'm not planning to push only "`stable`" updates so I will not need to do any rollback.
> 
> - `Facilitate greater visibility of tree changes through readable source control diffs.` When working with large codebases, it can be difficult to keep track of changes made to the project and understand the impact those changes may have on the codebase as a whole because of the potential different versions of packages, but since I'm only using exact versions in the `package.json` it does not affect this project in a major way the code base is not huge and I'm planning to try to reduce the package list by removing very small modules such as `is-html` or `is-url` for example and make my own "version" of them for the project.
> 
> And for the 2 others it doesn't really take a big time to install dependencies it's not slow on my side.
> 
> I'm not planning to include a `package-lock.json` for a project that only use exact modules versions and my mind will not change just because you decide to force for it to be pushed so I'm sorry but I will decline the `package-lock.json` push.

Alright have a great day

**Comment by Zaid-maker** [comment]
Sorry there was typo it's DevMirza#6447

**Pull request closed without merging**
